### ISSUE TITLE
info: menambahkan bot mergify untuk otomatisasi

### ISSUE THREAD

**Issue by slowy07** [bellshade/bellshade-website-v2#5]
Bot adalah kependekan dari “robot” yang dapat diartikan sebagai sistem untuk melakukan tugas tertentu secara otomatis dan repetitif. keuntungan dari bot antara lain:
- mengurangi kekeliruan pada tugas-tugas tertentu
- mengurangi beban kerja manusia

penggunaan bot **mergify** berfungsi apabila pull request sudah memehui beberapa syarat maka maintainer hanya menambahkan label _ready-to-merge_ maka bot akan otomatis merge hasil dari pull request ke dalam branch utama. cara pengunaannya adalah

1.  copy kode berikut ini
```yaml
pull_request_rules:
  # membuat requirement dari automerge dengan sistem
  # ketika workflow build passed maka akan dicentang
  # ketika target pull request ke main maka akan dicentang
  # ketika dikasih label 'ready-to-merge' akan dicentang

  # ketika requirement telah terpenuhi maka bot akan bekerja
  # dan pull request secara otomatis akan merge
  - name: merge ketika check sudah terpenuhi
    conditions:
      # di comment karena tidak memiliki unit testing github action
      # - check-success=build
      # jika pull request ke main maka akan dicentang
      - base=main
      # jika sudah menambahkan label ready to merge maka akan dicentang
      - label=ready-to-merge
    actions:
      # menambahkan komentar jika sudah di merge
      comment:
        message: terima kasih atas kontribusinya @{{author}}!
      # menambahkan label jika sudah di merge
      label:
        add: 
          - sudah dirieview!
      # metode sistem dari automerge
      merge:
        method: merge
  ```
2. kemudian simpan pada root folder dengan nama file ``.mergify`` 

**note**: **mergify** tidak akan bekerja PR jika file tersebut tidak terpasang pada folder root dari repositori.
